Add testing infrastructure
mudcoders/guildmud pull request #17
Opened 2018-02-05 18:24 UTC by rogersm

Some small steps to add testing infrastructure to close [Issue #11](https://github.com/mudcoders/guildmud/issues/11):

1. For the tests to run [Check](https://libcheck.github.io/check/) needs to be installed in your OS or vagrant.
2. Tests should be written in the $(ROOT)/tests/ directory using the [check syntax.
](https://stackoverflow.com/questions/14176180/is-there-a-more-basic-tutorial-for-the-c-unit-testing-framework-check) Additional info can be found reading the man page:
```shell
# man checkmk
```
3. Also, tests can be coded directly in C in $(ROOT)/tests/ directory, no problem with that. I plan to add a sample shortly, but if you do it before me and the Makefile is unable to compile them, please open an issue and I'll check.
4. Test samples are fairly inconsequential :)
5. The Makefile doesn't run the tests, this has to be done manually or via CI running the binaries compiled by the Makefile in $(ROOT)/tests/ directory. They can be identified by the .run extension. @zachflower can you add them to Travis CI?

2018-02-05 20:15 UTC, xenith commented on Makefile
> +C_FLAGS = -Wall -pedantic -Werror
Why are you disabling -g? I'd think we'd want debugging information in the binaries so core dumps are readable.

2018-02-06 19:06 UTC, zachflower requested changes
I think requiring `check` in macOS is fine, but let's make sure to keep the development environment in Vagrant up to date, since it can be provisioned automatically. Would you add a `check` provisioner, please?

There are two places to do this, the first is the provisioner script (take a look at `vagrant/provisioners/c.sh` for a solid example) and the second is in the `Vagrantfile` itself (where the provisioner scripts are executed).

2018-02-06 20:02 UTC, xenith approved these changes

2018-02-06 20:13 UTC, zachflower approved these changes

2018-02-06 20:14 UTC, merged